# version: "3.8"

# services:
#   mysqldb:
#     image: mysql:5.7
#     restart: unless-stopped
#     env_file: ./.env
#     environment:
#       - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
#       - MYSQL_DATABASE=$MYSQLDB_DATABASE
#     ports:
#       - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
#     volumes:
#       - db:/var/lib/mysql
#   app:
#     depends_on:
#       - mysqldb
#     build: .
#     restart: on-failure
#     env_file: ./.env
#     ports:
#       - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
#     environment:
      
#         "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false"
#         "spring.datasource.username" : "$MYSQLDB_USER"
#         "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD"
#         "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect"
#         "spring.jpa.hibernate.ddl-auto" : "update"
      
#     volumes:
#       - .m2:/root/.m2
#     stdin_open: true
#     tty: true

# volumes:
#   db:
version: "3.8"

services:
  service-discovery:
    build: ./serviceDiscovery/serviceDiscovery
    container_name: service-discovery
    restart: always
    ports:
      - 8761:8761
    expose:
      - 8761
  api-gateway:
    build: ./apigateway
    restart: always
    ports: 
      - 8081:8081
    depends_on:
      - service-discovery
    expose:
      - 8081
  server:
    build: .
    container_name: web-service
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
      - service-discovery
      - api-gateway
    links:
      - service-discovery
      - mysqldb
      - api-gateway
    expose:
      - 8080
  mysqldb:
    image: "mysql:8.0.33"
    container_name: mysql-database
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: roomrental
